development:
  adapter: postgresql
  encoding: unicode
  database: worldsblankestblank_development

test: &test
  adapter: postgresql
  encoding: unicode
  database: worldsblankestblank_test

production:
  adapter: postgresql
  encoding: unicode
  database: worldsblankestblank_production

cucumber:
  <<: *test
